[variables]
NIXPACKS_PHP_ROOT_DIR = "public"
NIXPACKS_PHP_EXTENSIONS = "intl, pdo_sqlite, sqlite3, gd, zip, mbstring, bcmath"
NIXPACKS_COMPOSER_INSTALL_ARGS = "--optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-intl"
