@extends('layouts.tool')

@section('title', 'Free 30-Day Content Calendar Generator & CSV Exporter - PostPilot')
@section('meta_description', 'Generate a structured 30-day social media matrix balancing 40% Educational, 30% Proof, 20% Story, and 10% Offer content with instant CSV export and one-click copying.')
@section('tool_name', 'Free 30-Day Content Calendar Generator')
@section('tool_route', 'tools.content-calendar-template')

@section('schema_json')
    <x-seo.faq-schema :faqs="[
        [
            'question' => 'What is a 30-day content calendar template?',
            'answer' => 'A 30-day content calendar template is a strategic roadmap used by marketers and creators to organize, schedule, and balance social media posts across a full month. It structures post angles into core content pillars—such as educational guides, social proof, founder stories, and promotional offers—to ensure consistent audience engagement and pipeline growth.'
        ],
        [
            'question' => 'How do I plan a social media content calendar?',
            'answer' => 'To plan an effective social media content calendar, start by defining your target audience and core business goals. Next, divide your monthly strategy into high-converting content pillars (like the 40/30/20/10 ratio) and map specific prompts, hook ideas, and target platforms for each day. Finally, batch-write your posts and export your schedule to a content planner or scheduling software.'
        ],
        [
            'question' => 'Can I export the content calendar as a CSV file?',
            'answer' => 'Yes, our tool allows you to export your customized 30-day content matrix into a clean, UTF-8 BOM encoded CSV file with one click. The exported CSV is directly compatible with Microsoft Excel, Google Sheets, Notion, and major social media scheduling tools like Buffer, Hootsuite, and Sprout Social.'
        ],
        [
            'question' => 'What types of content should I include in my calendar?',
            'answer' => 'A high-converting content calendar should mix four foundational content types: 40% educational value (how-to guides and frameworks), 30% social proof (case studies and client results), 20% story and vision (behind-the-scenes insights and personal lessons), and 10% direct offers (lead magnet promos and consultation calls-to-action).'
        ],
        [
            'question' => 'How often should I post on LinkedIn for best results?',
            'answer' => 'For optimal organic reach and audience engagement on LinkedIn, posting 3 to 5 times per week is recommended for most creators and B2B brands. Consistency matters more than extreme volume, so following a structured 30-day posting matrix helps you maintain quality while avoiding burnout.'
        ],
        [
            'question' => 'Does this tool work for multiple social media platforms?',
            'answer' => 'Yes, the content matrix prompts generated by this tool are tailored for major social platforms including LinkedIn, X (Twitter), Facebook, Instagram, and TikTok. You can dynamically adjust your target niche input to generate platform-specific post angles and execution tips for any industry.'
        ],
    ]" />
@endsection

@section('head')
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700;800&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<style>
    .font-sans {
        font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, sans-serif;
    }
    .font-mono {
        font-family: 'JetBrains Mono', monospace;
    }
    .material-symbols-outlined {
        font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;
    }
</style>
@endsection

@section('content')
<div class="mb-16 font-sans" x-data="calendarGenerator()">
    <!-- Toast Notification -->
    <div 
        x-show="toastVisible" 
        x-transition:enter="transition ease-out duration-300"
        x-transition:enter-start="opacity-0 translate-y-4 scale-95"
        x-transition:enter-end="opacity-100 translate-y-0 scale-100"
        x-transition:leave="transition ease-in duration-200"
        x-transition:leave-start="opacity-100 translate-y-0 scale-100"
        x-transition:leave-end="opacity-0 translate-y-4 scale-95"
        class="fixed bottom-6 right-6 z-50 bg-black text-white px-5 py-3.5 rounded-xl shadow-2xl border border-gray-700 font-mono text-xs font-bold flex items-center gap-3"
        x-cloak
    >
        <span class="material-symbols-outlined text-[#006c49] text-xl">check_circle</span>
        <span x-text="toastMessage"></span>
    </div>

    <!-- Centered Hero Section -->
    <section class="flex flex-col items-center text-center gap-4 max-w-3xl mx-auto mb-10 font-sans">
        <div class="inline-flex items-center gap-2 px-3.5 py-1.5 bg-[#006c49]/10 border border-[#006c49]/30 rounded-full shadow-md">
            <span class="material-symbols-outlined text-[16px] text-[#006c49]">verified</span>
            <span class="font-mono text-xs text-[#006c49] uppercase tracking-wider font-extrabold">PLANNING &amp; STRATEGY • 100% FREE &amp; CLIENT-SIDE</span>
        </div>
        <h1 class="text-3xl sm:text-4xl md:text-5xl font-extrabold text-black tracking-tight leading-tight font-sans text-center">
            30-Day Content Matrix Calendar Generator
        </h1>
        <p class="text-base sm:text-lg text-gray-600 max-w-2xl font-medium leading-relaxed text-center font-sans">
            Generate a high-converting 30-day social media schedule engineered with the proven 40% Educational / 30% Proof / 20% Story / 10% Offer growth matrix with instant CSV export and 1-click copy.
        </p>
    </section>

    {{-- GEO / Answer-First Content --}}
    <div class="max-w-3xl mx-auto mb-8 px-4 sm:px-0">
        <p class="text-[15px] leading-relaxed text-gray-700 font-medium bg-white border border-gray-200 rounded-xl p-5 shadow-sm">
            <strong>What is this tool?</strong> The 30-Day Content Calendar Template is a free utility that creates a complete monthly social media publishing strategy balanced across educational, proof, story, and offer content pillars. Content creators and marketers use it to eliminate planning burnout, maintain consistent posting habits, and convert followers into customers with instant CSV exports for scheduling tools.
        </p>
    </div>

    <!-- Top Quick Stats Bar -->
    <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
        <div class="bg-[#f3f4f6] border-2 border-gray-300 rounded-xl p-4 flex items-center gap-3.5 shadow-md hover:border-gray-400 transition-all">
            <div class="w-10 h-10 rounded-xl bg-black/5 border border-black/10 flex items-center justify-center text-black shrink-0">
                <span class="material-symbols-outlined text-xl">calendar_month</span>
            </div>
            <div>
                <div class="text-[10px] font-mono font-extrabold text-gray-500 uppercase tracking-wider">Total Matrix</div>
                <div class="text-base font-extrabold text-black font-mono">30 Days</div>
            </div>
        </div>
        <div class="bg-[#f3f4f6] border-2 border-gray-300 rounded-xl p-4 flex items-center gap-3.5 shadow-md hover:border-gray-400 transition-all">
            <div class="w-10 h-10 rounded-xl bg-[#006c49]/10 border border-[#006c49]/20 flex items-center justify-center text-[#006c49] shrink-0">
                <span class="material-symbols-outlined text-xl">pie_chart</span>
            </div>
            <div>
                <div class="text-[10px] font-mono font-extrabold text-gray-500 uppercase tracking-wider">Pillar Ratio</div>
                <div class="text-base font-extrabold text-black font-mono">40 / 30 / 20 / 10</div>
            </div>
        </div>
        <div class="bg-[#f3f4f6] border-2 border-gray-300 rounded-xl p-4 flex items-center gap-3.5 shadow-md hover:border-gray-400 transition-all">
            <div class="w-10 h-10 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center text-blue-600 shrink-0">
                <span class="material-symbols-outlined text-xl">tune</span>
            </div>
            <div>
                <div class="text-[10px] font-mono font-extrabold text-gray-500 uppercase tracking-wider">Niche Customization</div>
                <div class="text-base font-extrabold text-black font-mono">Real-Time</div>
            </div>
        </div>
        <div class="bg-[#f3f4f6] border-2 border-gray-300 rounded-xl p-4 flex items-center gap-3.5 shadow-md hover:border-gray-400 transition-all">
            <div class="w-10 h-10 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-600 shrink-0">
                <span class="material-symbols-outlined text-xl">download</span>
            </div>
            <div>
                <div class="text-[10px] font-mono font-extrabold text-gray-500 uppercase tracking-wider">Format</div>
                <div class="text-base font-extrabold text-black font-mono">UTF-8 BOM CSV</div>
            </div>
        </div>
    </div>

    <!-- Workspace Control Card: Niche Input & Global Actions -->
    <div class="bg-[#f8f9fa] border-2 border-gray-300 rounded-[1rem] p-6 sm:p-8 shadow-md mb-8 space-y-6">
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-6 items-end">
            <!-- Niche Input -->
            <div class="lg:col-span-6 space-y-2">
                <label for="nicheInput" class="block text-xs font-extrabold uppercase tracking-wider text-black font-mono flex items-center justify-between">
                    <span class="flex items-center gap-2">
                        <span class="material-symbols-outlined text-base text-[#006c49]">work</span>
                        Your Industry / Target Niche
                    </span>
                    <span class="text-gray-400 font-normal normal-case text-[11px] hidden sm:inline font-sans">Updates all 30 prompt angles dynamically</span>
                </label>
                <div class="relative">
                    <input 
                        id="nicheInput"
                        type="text" 
                        x-model="niche" 
                        @input="generateCalendar()"
                        placeholder="e.g. B2B SaaS, E-commerce DTC, Real Estate, Fitness Coach, Marketing Agency" 
                        class="w-full bg-white border-2 border-gray-300 focus:border-black focus:ring-2 focus:ring-black/10 rounded-xl pl-4 pr-20 py-3.5 text-sm text-gray-900 font-semibold focus:outline-none transition-all placeholder:text-gray-400 shadow-md"
                    >
                    <button 
                        type="button"
                        x-show="niche.length > 0" 
                        @click="niche = ''; generateCalendar()" 
                        class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-black text-xs font-mono font-bold px-2 py-1 transition-colors rounded-lg"
                        title="Clear niche"
                        x-cloak
                    >
                        Clear
                    </button>
                </div>
            </div>

            <!-- Export & Batch Copy Buttons -->
            <div class="lg:col-span-6 flex flex-col sm:flex-row items-center gap-3">
                <button 
                    type="button"
                    @click="exportCsv()"
                    class="w-full sm:w-1/2 bg-black hover:bg-[#006c49] text-white font-mono font-bold text-xs uppercase tracking-wider rounded-xl border-2 border-black hover:border-[#006c49] shadow-md transition-all flex items-center justify-center gap-2 px-5 py-4 cursor-pointer active:scale-[0.98] group"
                >
                    <span class="material-symbols-outlined text-lg group-hover:translate-y-0.5 transition-transform">download</span>
                    <span>Export 30-Day CSV</span>
                </button>
                <button 
                    type="button"
                    @click="copyAllPrompts()"
                    class="w-full sm:w-1/2 bg-white hover:bg-black hover:text-white text-gray-800 font-mono font-bold text-xs uppercase tracking-wider rounded-xl border-2 border-gray-300 hover:border-black shadow-md transition-all flex items-center justify-center gap-2 px-5 py-4 cursor-pointer active:scale-[0.98]"
                >
                    <span class="material-symbols-outlined text-lg text-gray-500 group-hover:text-white">content_copy</span>
                    <span>Copy All 30 Days</span>
                </button>
            </div>
        </div>

        <!-- Quick Niche Presets -->
        <div class="pt-4 border-t border-gray-200">
            <div class="flex flex-wrap items-center gap-2">
                <span class="text-xs font-mono font-extrabold text-gray-500 uppercase tracking-wider mr-1 flex items-center gap-1">
                    <span class="material-symbols-outlined text-sm text-[#006c49]">bolt</span> Presets:
                </span>
                <template x-for="preset in presets" :key="preset">
                    <button 
                        type="button"
                        @click="setNiche(preset)"
                        class="text-xs font-mono font-semibold px-3.5 py-1.5 rounded-xl border-2 transition-all cursor-pointer active:scale-95"
                        :class="niche === preset ? 'bg-black text-white border-black shadow-md' : 'bg-white hover:bg-gray-50 text-gray-700 border-gray-300 hover:border-gray-400'"
                        x-text="preset"
                    ></button>
                </template>
            </div>
        </div>
    </div>

    <!-- Strategic Ratio Breakdown Cards (4 Interactive Pillar Cards) -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <!-- Educational (40%) -->
        <div 
            @click="activePillar = activePillar === 'Educational' ? 'all' : 'Educational'"
            class="bg-white border-2 rounded-xl p-5 shadow-md space-y-3 relative overflow-hidden transition-all cursor-pointer group"
            :class="activePillar === 'Educational' ? 'border-blue-600 ring-2 ring-blue-500/20' : 'border-gray-300 hover:border-blue-400'"
        >
            <div class="flex items-center justify-between">
                <span class="font-mono text-[10px] font-extrabold uppercase tracking-wider text-blue-900 bg-blue-50 border border-blue-200 px-3 py-1 rounded-full flex items-center gap-1">
                    <span class="material-symbols-outlined text-xs">school</span>
                    Educational
                </span>
                <span class="font-mono text-xs font-extrabold text-blue-950 bg-blue-100 px-2 py-0.5 rounded-lg border border-blue-200">40%</span>
            </div>
            <div class="flex items-baseline gap-2">
                <span class="text-3xl font-black font-mono text-black" x-text="pillarCounts.Educational || 12">12</span>
                <span class="text-xs text-gray-500 font-mono font-bold">Days</span>
            </div>
            <p class="text-xs text-gray-600 leading-relaxed font-sans">
                How-tos, frameworks, mistake breakdowns &amp; step-by-step tactical guides.
            </p>
        </div>

        <!-- Proof (30%) -->
        <div 
            @click="activePillar = activePillar === 'Proof' ? 'all' : 'Proof'"
            class="bg-white border-2 rounded-xl p-5 shadow-md space-y-3 relative overflow-hidden transition-all cursor-pointer group"
            :class="activePillar === 'Proof' ? 'border-[#006c49] ring-2 ring-emerald-500/20' : 'border-gray-300 hover:border-emerald-400'"
        >
            <div class="flex items-center justify-between">
                <span class="font-mono text-[10px] font-extrabold uppercase tracking-wider text-emerald-900 bg-emerald-50 border border-emerald-200 px-3 py-1 rounded-full flex items-center gap-1">
                    <span class="material-symbols-outlined text-xs">verified</span>
                    Social Proof
                </span>
                <span class="font-mono text-xs font-extrabold text-emerald-950 bg-emerald-100 px-2 py-0.5 rounded-lg border border-emerald-200">30%</span>
            </div>
            <div class="flex items-baseline gap-2">
                <span class="text-3xl font-black font-mono text-black" x-text="pillarCounts.Proof || 9">9</span>
                <span class="text-xs text-gray-500 font-mono font-bold">Days</span>
            </div>
            <p class="text-xs text-gray-600 leading-relaxed font-sans">
                Case studies, metrics breakdowns, before/after results &amp; client proof.
            </p>
        </div>

        <!-- Story (20%) -->
        <div 
            @click="activePillar = activePillar === 'Story' ? 'all' : 'Story'"
            class="bg-white border-2 rounded-xl p-5 shadow-md space-y-3 relative overflow-hidden transition-all cursor-pointer group"
            :class="activePillar === 'Story' ? 'border-purple-600 ring-2 ring-purple-500/20' : 'border-gray-300 hover:border-purple-400'"
        >
            <div class="flex items-center justify-between">
                <span class="font-mono text-[10px] font-extrabold uppercase tracking-wider text-purple-900 bg-purple-50 border border-purple-200 px-3 py-1 rounded-full flex items-center gap-1">
                    <span class="material-symbols-outlined text-xs">auto_stories</span>
                    Story & Vision
                </span>
                <span class="font-mono text-xs font-extrabold text-purple-950 bg-purple-100 px-2 py-0.5 rounded-lg border border-purple-200">20%</span>
            </div>
            <div class="flex items-baseline gap-2">
                <span class="text-3xl font-black font-mono text-black" x-text="pillarCounts.Story || 6">6</span>
                <span class="text-xs text-gray-500 font-mono font-bold">Days</span>
            </div>
            <p class="text-xs text-gray-600 leading-relaxed font-sans">
                Founder journey, behind-the-scenes failures, lessons learned &amp; vision.
            </p>
        </div>

        <!-- Offer (10%) -->
        <div 
            @click="activePillar = activePillar === 'Offer' ? 'all' : 'Offer'"
            class="bg-white border-2 rounded-xl p-5 shadow-md space-y-3 relative overflow-hidden transition-all cursor-pointer group"
            :class="activePillar === 'Offer' ? 'border-amber-600 ring-2 ring-amber-500/20' : 'border-gray-300 hover:border-amber-400'"
        >
            <div class="flex items-center justify-between">
                <span class="font-mono text-[10px] font-extrabold uppercase tracking-wider text-amber-900 bg-amber-50 border border-amber-200 px-3 py-1 rounded-full flex items-center gap-1">
                    <span class="material-symbols-outlined text-xs">campaign</span>
                    Direct Offer
                </span>
                <span class="font-mono text-xs font-extrabold text-amber-950 bg-amber-100 px-2 py-0.5 rounded-lg border border-amber-200">10%</span>
            </div>
            <div class="flex items-baseline gap-2">
                <span class="text-3xl font-black font-mono text-black" x-text="pillarCounts.Offer || 3">3</span>
                <span class="text-xs text-gray-500 font-mono font-bold">Days</span>
            </div>
            <p class="text-xs text-gray-600 leading-relaxed font-sans">
                Product intro, free audit invitations, lead magnet promos &amp; clear CTAs.
            </p>
        </div>
    </div>

    <!-- Filter Bar: Week Tabs, Pillar Chips, Search & Copy Active Week -->
    <div class="bg-[#f8f9fa] border-2 border-gray-300 rounded-[1rem] p-4 sm:p-6 shadow-md mb-6 space-y-4">
        <div class="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
            <!-- Week Tabs -->
            <div class="flex flex-wrap items-center gap-2">
                <button 
                    type="button"
                    @click="activeTab = 'all'" 
                    class="px-3.5 py-2 rounded-xl text-xs font-mono font-bold transition-all cursor-pointer border-2 active:scale-95"
                    :class="activeTab === 'all' ? 'bg-black text-white border-black shadow-md' : 'bg-white hover:bg-gray-50 text-gray-700 border-gray-300'"
                >
                    All Days (30)
                </button>
                <button 
                    type="button"
                    @click="activeTab = 'week1'" 
                    class="px-3.5 py-2 rounded-xl text-xs font-mono font-bold transition-all cursor-pointer border-2 active:scale-95"
                    :class="activeTab === 'week1' ? 'bg-black text-white border-black shadow-md' : 'bg-white hover:bg-gray-50 text-gray-700 border-gray-300'"
                >
                    W1 (Days 1-7)
                </button>
                <button 
                    type="button"
                    @click="activeTab = 'week2'" 
                    class="px-3.5 py-2 rounded-xl text-xs font-mono font-bold transition-all cursor-pointer border-2 active:scale-95"
                    :class="activeTab === 'week2' ? 'bg-black text-white border-black shadow-md' : 'bg-white hover:bg-gray-50 text-gray-700 border-gray-300'"
                >
                    W2 (Days 8-14)
                </button>
                <button 
                    type="button"
                    @click="activeTab = 'week3'" 
                    class="px-3.5 py-2 rounded-xl text-xs font-mono font-bold transition-all cursor-pointer border-2 active:scale-95"
                    :class="activeTab === 'week3' ? 'bg-black text-white border-black shadow-md' : 'bg-white hover:bg-gray-50 text-gray-700 border-gray-300'"
                >
                    W3 (Days 15-21)
                </button>
                <button 
                    type="button"
                    @click="activeTab = 'week4'" 
                    class="px-3.5 py-2 rounded-xl text-xs font-mono font-bold transition-all cursor-pointer border-2 active:scale-95"
                    :class="activeTab === 'week4' ? 'bg-black text-white border-black shadow-md' : 'bg-white hover:bg-gray-50 text-gray-700 border-gray-300'"
                >
                    W4 (Days 22-28)
                </button>
                <button 
                    type="button"
                    @click="activeTab = 'week5'" 
                    class="px-3.5 py-2 rounded-xl text-xs font-mono font-bold transition-all cursor-pointer border-2 active:scale-95"
                    :class="activeTab === 'week5' ? 'bg-black text-white border-black shadow-md' : 'bg-white hover:bg-gray-50 text-gray-700 border-gray-300'"
                >
                    W5 (Days 29-30)
                </button>
            </div>

            <!-- Right Actions: Copy Active View & Search Input -->
            <div class="flex items-center gap-3 w-full lg:w-auto">
                <button 
                    type="button"
                    @click="copyActiveWeekPrompts()"
                    class="px-3.5 py-2 rounded-xl bg-white hover:bg-[#006c49] text-gray-800 hover:text-white border-2 border-gray-300 hover:border-[#006c49] font-mono text-xs font-bold transition-all flex items-center gap-1.5 shadow-sm shrink-0 cursor-pointer active:scale-95"
                    title="Copy all prompts in the current week filter"
                >
                    <span class="material-symbols-outlined text-base">copy_all</span>
                    <span x-text="activeTab === 'all' ? 'Copy All Visible' : 'Copy Active Week'"></span>
                </button>

                <div class="w-full lg:w-64 relative">
                    <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                        <span class="material-symbols-outlined text-base">search</span>
                    </div>
                    <input 
                        type="text" 
                        x-model="searchQuery"
                        placeholder="Search prompts..." 
                        class="w-full bg-white border-2 border-gray-300 focus:border-black focus:ring-2 focus:ring-black/10 rounded-xl pl-9 pr-8 py-2 text-xs text-gray-900 font-medium focus:outline-none transition-all placeholder:text-gray-400 shadow-md"
                    >
                    <button 
                        type="button"
                        x-show="searchQuery.length > 0" 
                        @click="searchQuery = ''" 
                        class="absolute right-2.5 top-1/2 -translate-y-1/2 text-gray-400 hover:text-black text-xs font-mono"
                        x-cloak
                    >
                        ✕
                    </button>
                </div>
            </div>
        </div>

        <!-- Strategy Pillar Filter Chips -->
        <div class="pt-3 border-t border-gray-200 flex flex-wrap items-center gap-2">
            <span class="text-xs font-mono font-extrabold text-gray-500 uppercase tracking-wider mr-1">Filter Pillar:</span>
            <button 
                type="button"
                @click="activePillar = 'all'"
                class="px-3 py-1 rounded-xl text-[11px] font-mono font-bold border-2 transition-all cursor-pointer active:scale-95"
                :class="activePillar === 'all' ? 'bg-black text-white border-black' : 'bg-white hover:bg-gray-50 text-gray-700 border-gray-300'"
            >
                All Pillars
            </button>
            <button 
                type="button"
                @click="activePillar = 'Educational'"
                class="px-3 py-1 rounded-xl text-[11px] font-mono font-bold border-2 transition-all cursor-pointer active:scale-95"
                :class="activePillar === 'Educational' ? 'bg-blue-600 text-white border-blue-600' : 'bg-blue-50 hover:bg-blue-100 text-blue-900 border-blue-200'"
            >
                Educational (40%)
            </button>
            <button 
                type="button"
                @click="activePillar = 'Proof'"
                class="px-3 py-1 rounded-xl text-[11px] font-mono font-bold border-2 transition-all cursor-pointer active:scale-95"
                :class="activePillar === 'Proof' ? 'bg-[#006c49] text-white border-[#006c49]' : 'bg-emerald-50 hover:bg-emerald-100 text-emerald-900 border-emerald-200'"
            >
                Social Proof (30%)
            </button>
            <button 
                type="button"
                @click="activePillar = 'Story'"
                class="px-3 py-1 rounded-xl text-[11px] font-mono font-bold border-2 transition-all cursor-pointer active:scale-95"
                :class="activePillar === 'Story' ? 'bg-purple-600 text-white border-purple-600' : 'bg-purple-50 hover:bg-purple-100 text-purple-900 border-purple-200'"
            >
                Story & Vision (20%)
            </button>
            <button 
                type="button"
                @click="activePillar = 'Offer'"
                class="px-3 py-1 rounded-xl text-[11px] font-mono font-bold border-2 transition-all cursor-pointer active:scale-95"
                :class="activePillar === 'Offer' ? 'bg-amber-600 text-white border-amber-600' : 'bg-amber-50 hover:bg-amber-100 text-amber-900 border-amber-200'"
            >
                Direct Offer (10%)
            </button>
        </div>
    </div>

    <!-- Calendar Table Matrix Card -->
    <div class="bg-white border-2 border-gray-300 rounded-[1rem] overflow-hidden shadow-md">
        <div class="overflow-x-auto">
            <table class="w-full text-left text-xs text-gray-700">
                <thead class="bg-[#f8f9fa] text-black uppercase font-extrabold text-[11px] tracking-wider border-b-2 border-gray-300 font-mono">
                    <tr>
                        <th class="py-4 px-5 w-24">Day</th>
                        <th class="py-4 px-5 w-40">Pillar Type</th>
                        <th class="py-4 px-5">Post Prompt / Strategy Angle</th>
                        <th class="py-4 px-5 w-36">Target Platform</th>
                        <th class="py-4 px-5 w-48 text-right">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200">
                    <template x-for="row in filteredDays" :key="row.day">
                        <tr class="hover:bg-[#f8f9fa] transition-colors group">
                            <!-- Day Number -->
                            <td class="py-4 px-5 font-mono font-extrabold text-black text-sm whitespace-nowrap" x-text="`Day ${row.day.toString().padStart(2, '0')}`"></td>
                            
                            <!-- Pillar Badge -->
                            <td class="py-4 px-5 whitespace-nowrap">
                                <span 
                                    class="px-3 py-1 rounded-full text-[10px] font-extrabold uppercase tracking-wider inline-flex items-center gap-1 font-mono border"
                                    :class="{
                                        'bg-blue-50 text-blue-900 border-blue-200': row.pillar === 'Educational',
                                        'bg-emerald-50 text-emerald-900 border-emerald-200': row.pillar === 'Proof',
                                        'bg-purple-50 text-purple-900 border-purple-200': row.pillar === 'Story',
                                        'bg-amber-50 text-amber-900 border-amber-200': row.pillar === 'Offer'
                                    }"
                                    x-text="row.pillar === 'Proof' ? 'Social Proof' : (row.pillar === 'Story' ? 'Story & Vision' : row.pillar)"
                                ></span>
                            </td>

                            <!-- Prompt Angle -->
                            <td class="py-4 px-5 text-gray-900 font-medium leading-relaxed font-sans text-xs sm:text-sm">
                                <div class="flex items-center justify-between gap-2">
                                    <span x-text="row.prompt"></span>
                                </div>
                            </td>

                            <!-- Target Platform -->
                            <td class="py-4 px-5 whitespace-nowrap">
                                <span class="px-2.5 py-1 bg-[#f3f4f6] text-gray-800 rounded-lg border border-gray-300 font-mono text-[11px] font-bold" x-text="row.platform"></span>
                            </td>

                            <!-- Actions Buttons -->
                            <td class="py-4 px-5 text-right whitespace-nowrap">
                                <div class="inline-flex items-center justify-end gap-2">
                                    <button 
                                        type="button"
                                        @click="openModal(row)"
                                        class="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-xl border border-gray-300 bg-white hover:bg-gray-100 text-gray-700 text-[11px] font-mono font-bold transition-all cursor-pointer"
                                        title="Preview strategy & prompt details"
                                    >
                                        <span class="material-symbols-outlined text-sm text-gray-500">visibility</span>
                                        <span>Preview</span>
                                    </button>

                                    <button 
                                        type="button"
                                        @click="copyPrompt(row.prompt, row.day)"
                                        class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border-2 border-gray-300 bg-white hover:bg-black hover:text-white hover:border-black active:scale-95 text-gray-800 text-[11px] font-mono font-bold transition-all cursor-pointer shadow-sm"
                                    >
                                        <template x-if="copiedDay === row.day">
                                            <span class="text-[#006c49] flex items-center gap-1">
                                                <span class="material-symbols-outlined text-sm text-[#006c49]">check_circle</span>
                                                Copied!
                                            </span>
                                        </template>
                                        <template x-if="copiedDay !== row.day">
                                            <span class="flex items-center gap-1">
                                                <span class="material-symbols-outlined text-sm text-gray-400 group-hover:text-white">content_copy</span>
                                                Copy
                                            </span>
                                        </template>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </template>

                    <template x-if="filteredDays.length === 0">
                        <tr>
                            <td colspan="5" class="py-12 text-center text-gray-500 font-mono text-xs">
                                <div class="max-w-xs mx-auto space-y-2">
                                    <span class="material-symbols-outlined text-3xl text-gray-300">search_off</span>
                                    <p class="font-bold text-gray-700">No matching prompts found</p>
                                    <p class="text-gray-400 text-[11px]">Try adjusting your search query or reset your week and pillar filters.</p>
                                </div>
                            </td>
                        </tr>
                    </template>
                </tbody>
            </table>
        </div>
    </div>

    <!-- Prompt Preview Modal -->
    <div 
        x-show="modalOpen" 
        x-transition:enter="transition ease-out duration-300"
        x-transition:enter-start="opacity-0"
        x-transition:enter-end="opacity-100"
        x-transition:leave="transition ease-in duration-200"
        x-transition:leave-start="opacity-100"
        x-transition:leave-end="opacity-0"
        class="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/60 backdrop-blur-sm"
        @keydown.escape.window="modalOpen = false"
        x-cloak
    >
        <div 
            @click.outside="modalOpen = false"
            class="bg-white border-2 border-black rounded-2xl p-6 sm:p-8 shadow-2xl max-w-xl w-full space-y-6 relative max-h-[90vh] overflow-y-auto"
        >
            <!-- Modal Header -->
            <div class="flex items-center justify-between border-b border-gray-200 pb-4">
                <div class="flex items-center gap-3">
                    <span class="font-mono text-sm font-extrabold text-black bg-gray-100 px-3 py-1 rounded-lg border border-gray-300" x-text="`Day ${selectedRow?.day}`"></span>
                    <span 
                        class="px-3 py-1 rounded-full text-[10px] font-extrabold uppercase tracking-wider inline-flex items-center gap-1 font-mono border"
                        :class="{
                            'bg-blue-50 text-blue-900 border-blue-200': selectedRow?.pillar === 'Educational',
                            'bg-emerald-50 text-emerald-900 border-emerald-200': selectedRow?.pillar === 'Proof',
                            'bg-purple-50 text-purple-900 border-purple-200': selectedRow?.pillar === 'Story',
                            'bg-amber-50 text-amber-900 border-amber-200': selectedRow?.pillar === 'Offer'
                        }"
                        x-text="selectedRow?.pillar === 'Proof' ? 'Social Proof' : (selectedRow?.pillar === 'Story' ? 'Story & Vision' : selectedRow?.pillar)"
                    ></span>
                </div>
                <button type="button" @click="modalOpen = false" class="text-gray-400 hover:text-black transition-colors p-1 rounded-lg hover:bg-gray-100 cursor-pointer">
                    <span class="material-symbols-outlined text-xl">close</span>
                </button>
            </div>

            <!-- Content Prompt Box -->
            <div class="space-y-2">
                <label class="text-[11px] font-mono font-extrabold text-gray-500 uppercase tracking-wider">Post Prompt &amp; Strategy Angle</label>
                <div class="bg-[#f8f9fa] border-2 border-gray-300 rounded-xl p-4 text-gray-900 text-base font-semibold leading-relaxed font-sans" x-text="selectedRow?.prompt"></div>
            </div>

            <!-- Strategy Details Grid -->
            <div class="grid grid-cols-2 gap-4 text-xs font-mono">
                <div class="bg-gray-50 border border-gray-200 rounded-xl p-3.5 space-y-1">
                    <span class="text-gray-500 text-[10px] uppercase tracking-wider font-extrabold block">Target Platform</span>
                    <span class="text-black font-bold text-sm block" x-text="selectedRow?.platform"></span>
                </div>
                <div class="bg-gray-50 border border-gray-200 rounded-xl p-3.5 space-y-1">
                    <span class="text-gray-500 text-[10px] uppercase tracking-wider font-extrabold block">Recommended Format</span>
                    <span class="text-black font-bold text-sm block" x-text="selectedRow?.format"></span>
                </div>
            </div>

            <!-- Strategic Execution Tip -->
            <div class="bg-emerald-50 border border-emerald-200 rounded-xl p-4 text-xs text-emerald-950 space-y-1 font-sans">
                <div class="font-bold font-mono text-[11px] uppercase tracking-wider text-[#006c49] flex items-center gap-1.5">
                    <span class="material-symbols-outlined text-sm">lightbulb</span> Strategic Execution Tip
                </div>
                <p class="leading-relaxed" x-text="selectedRow?.tip"></p>
            </div>

            <!-- Modal Footer Actions -->
            <div class="flex items-center justify-end gap-3 pt-2 border-t border-gray-100">
                <button 
                    type="button" 
                    @click="modalOpen = false"
                    class="px-4 py-2.5 rounded-xl border-2 border-gray-300 hover:border-gray-400 font-mono text-xs font-bold text-gray-700 hover:bg-gray-50 transition-all cursor-pointer"
                >
                    Close
                </button>
                <button 
                    type="button" 
                    @click="copyPrompt(selectedRow?.prompt, selectedRow?.day); modalOpen = false"
                    class="px-5 py-2.5 rounded-xl bg-[#006c49] hover:bg-[#005237] text-white border-2 border-[#006c49] font-mono text-xs font-bold shadow-md transition-all flex items-center gap-2 cursor-pointer"
                >
                    <span class="material-symbols-outlined text-sm">content_copy</span>
                    Copy Prompt Text
                </button>
            </div>
        </div>
    </div>

    <!-- Educational & Strategy Guide Section -->
    <div class="mt-12 grid grid-cols-1 md:grid-cols-2 gap-8">
        <div class="bg-[#f8f9fa] border-2 border-gray-300 rounded-[1rem] p-6 sm:p-8 space-y-4">
            <h3 class="text-lg font-extrabold text-black font-sans flex items-center gap-2">
                <span class="material-symbols-outlined text-[#006c49]">grid_view</span>
                How the 40/30/20/10 Matrix Works
            </h3>
            <p class="text-xs sm:text-sm text-gray-600 leading-relaxed">
                Consistency without strategic intent leads to audience fatigue. The 40/30/20/10 Content Matrix balances trust-building value with audience conversion:
            </p>
            <ul class="space-y-2 text-xs sm:text-sm text-gray-700 font-medium">
                <li class="flex items-start gap-2">
                    <span class="w-2 h-2 rounded-full bg-blue-500 mt-1.5 shrink-0"></span>
                    <span><strong>40% Educational:</strong> High-value tactical frameworks, how-tos, and actionable guides that solve immediate audience problems.</span>
                </li>
                <li class="flex items-start gap-2">
                    <span class="w-2 h-2 rounded-full bg-emerald-500 mt-1.5 shrink-0"></span>
                    <span><strong>30% Social Proof:</strong> Real client results, teardowns, case studies, and quantifiable transformations.</span>
                </li>
                <li class="flex items-start gap-2">
                    <span class="w-2 h-2 rounded-full bg-purple-500 mt-1.5 shrink-0"></span>
                    <span><strong>20% Story &amp; Vision:</strong> Behind-the-scenes insights, founder lessons, personal stories, and brand mission.</span>
                </li>
                <li class="flex items-start gap-2">
                    <span class="w-2 h-2 rounded-full bg-amber-500 mt-1.5 shrink-0"></span>
                    <span><strong>10% Direct Offer:</strong> High-converting calls-to-action, product announcements, and consultation invitations.</span>
                </li>
            </ul>
        </div>

        <div class="bg-[#f8f9fa] border-2 border-gray-300 rounded-[1rem] p-6 sm:p-8 space-y-4">
            <h3 class="text-lg font-extrabold text-black font-sans flex items-center gap-2">
                <span class="material-symbols-outlined text-[#006c49]">table_view</span>
                CSV Export &amp; Workflow Tips
            </h3>
            <p class="text-xs sm:text-sm text-gray-600 leading-relaxed">
                Exporting your matrix to CSV unlocks seamless content operations across your organization:
            </p>
            <ul class="space-y-2 text-xs sm:text-sm text-gray-700 font-medium">
                <li class="flex items-start gap-2">
                    <span class="material-symbols-outlined text-base text-[#006c49] shrink-0">check_circle</span>
                    <span><strong>UTF-8 BOM Encoded:</strong> Compatible out-of-the-box with Microsoft Excel, Apple Numbers, and Google Sheets without character corruption.</span>
                </li>
                <li class="flex items-start gap-2">
                    <span class="material-symbols-outlined text-base text-[#006c49] shrink-0">check_circle</span>
                    <span><strong>Social Scheduler Ready:</strong> Import directly into Notion, Buffer, Hootsuite, or Sprout Social to schedule posts in bulk.</span>
                </li>
                <li class="flex items-start gap-2">
                    <span class="material-symbols-outlined text-base text-[#006c49] shrink-0">check_circle</span>
                    <span><strong>Dynamic Customization:</strong> Change the target niche input at any time to regenerate 30 distinct prompt angles customized for your market.</span>
                </li>
            </ul>
        </div>
    </div>

    {{-- FAQ Section (SSR Content for SEO) --}}
    <section class="mt-16 max-w-4xl mx-auto" x-data="{ openFaq: null }">
        <div class="flex items-center gap-3 mb-8">
            <span class="material-symbols-outlined text-[#006c49] text-xl">help</span>
            <h2 class="text-xl font-extrabold text-black tracking-tight font-sans">Frequently Asked Questions</h2>
        </div>

        @php
            $faqs = [
                [
                    'question' => 'What is a 30-day content calendar template?',
                    'answer' => 'A 30-day content calendar template is a strategic roadmap used by marketers and creators to organize, schedule, and balance social media posts across a full month. It structures post angles into core content pillars—such as educational guides, social proof, founder stories, and promotional offers—to ensure consistent audience engagement and pipeline growth.'
                ],
                [
                    'question' => 'How do I plan a social media content calendar?',
                    'answer' => 'To plan an effective social media content calendar, start by defining your target audience and core business goals. Next, divide your monthly strategy into high-converting content pillars (like the 40/30/20/10 ratio) and map specific prompts, hook ideas, and target platforms for each day. Finally, batch-write your posts and export your schedule to a content planner or scheduling software.'
                ],
                [
                    'question' => 'Can I export the content calendar as a CSV file?',
                    'answer' => 'Yes, our tool allows you to export your customized 30-day content matrix into a clean, UTF-8 BOM encoded CSV file with one click. The exported CSV is directly compatible with Microsoft Excel, Google Sheets, Notion, and major social media scheduling tools like Buffer, Hootsuite, and Sprout Social.'
                ],
                [
                    'question' => 'What types of content should I include in my calendar?',
                    'answer' => 'A high-converting content calendar should mix four foundational content types: 40% educational value (how-to guides and frameworks), 30% social proof (case studies and client results), 20% story and vision (behind-the-scenes insights and personal lessons), and 10% direct offers (lead magnet promos and consultation calls-to-action).'
                ],
                [
                    'question' => 'How often should I post on LinkedIn for best results?',
                    'answer' => 'For optimal organic reach and audience engagement on LinkedIn, posting 3 to 5 times per week is recommended for most creators and B2B brands. Consistency matters more than extreme volume, so following a structured 30-day posting matrix helps you maintain quality while avoiding burnout.'
                ],
                [
                    'question' => 'Does this tool work for multiple social media platforms?',
                    'answer' => 'Yes, the content matrix prompts generated by this tool are tailored for major social platforms including LinkedIn, X (Twitter), Facebook, Instagram, and TikTok. You can dynamically adjust your target niche input to generate platform-specific post angles and execution tips for any industry.'
                ],
            ];
        @endphp

        <div class="space-y-3">
            @foreach($faqs as $index => $faq)
            <div class="border border-gray-200 rounded-xl overflow-hidden bg-white">
                <button
                    @click="openFaq = openFaq === {{ $index }} ? null : {{ $index }}"
                    class="w-full flex items-center justify-between p-5 text-left hover:bg-gray-50 transition-colors"
                    :aria-expanded="openFaq === {{ $index }}">
                    <span class="text-sm font-bold text-black pr-4">{{ $faq['question'] }}</span>
                    <span class="material-symbols-outlined text-gray-400 transition-transform duration-200 flex-shrink-0"
                          :class="openFaq === {{ $index }} && 'rotate-180'">expand_more</span>
                </button>
                <div x-show="openFaq === {{ $index }}"
                     x-transition:enter="transition ease-out duration-200"
                     x-transition:enter-start="opacity-0 -translate-y-1"
                     x-transition:enter-end="opacity-100 translate-y-0"
                     x-cloak
                     class="px-5 pb-5 text-sm text-gray-600 leading-relaxed border-t border-gray-100">
                    <p class="pt-4">{{ $faq['answer'] }}</p>
                </div>
            </div>
            @endforeach
        </div>
    </section>
</div>

<script>
function calendarGenerator() {
    return {
        niche: 'B2B SaaS',
        days: [],
        activeTab: 'all',
        activePillar: 'all',
        searchQuery: '',
        copiedDay: null,
        modalOpen: false,
        selectedRow: null,
        toastVisible: false,
        toastMessage: '',
        presets: ['B2B SaaS', 'E-commerce DTC', 'Real Estate', 'Fitness Coach', 'Personal Brand', 'Marketing Agency', 'Solopreneur'],

        init() {
            this.generateCalendar();
        },

        setNiche(preset) {
            this.niche = preset;
            this.generateCalendar();
        },

        showToast(msg) {
            this.toastMessage = msg;
            this.toastVisible = true;
            setTimeout(() => {
                this.toastVisible = false;
            }, 2500);
        },

        openModal(row) {
            this.selectedRow = row;
            this.modalOpen = true;
        },

        get pillarCounts() {
            const counts = { Educational: 0, Proof: 0, Story: 0, Offer: 0 };
            this.days.forEach(d => {
                if (counts[d.pillar] !== undefined) {
                    counts[d.pillar]++;
                }
            });
            return counts;
        },

        get filteredDays() {
            const q = (this.searchQuery || '').trim().toLowerCase();
            return this.days.filter(row => {
                // Tab filter
                let tabMatch = true;
                if (this.activeTab === 'week1') tabMatch = row.day >= 1 && row.day <= 7;
                else if (this.activeTab === 'week2') tabMatch = row.day >= 8 && row.day <= 14;
                else if (this.activeTab === 'week3') tabMatch = row.day >= 15 && row.day <= 21;
                else if (this.activeTab === 'week4') tabMatch = row.day >= 22 && row.day <= 28;
                else if (this.activeTab === 'week5') tabMatch = row.day >= 29 && row.day <= 30;

                // Pillar filter
                let pillarMatch = true;
                if (this.activePillar !== 'all') {
                    pillarMatch = row.pillar === this.activePillar;
                }

                // Search query filter
                let searchMatch = true;
                if (q !== '') {
                    searchMatch = row.prompt.toLowerCase().includes(q) ||
                                 row.pillar.toLowerCase().includes(q) ||
                                 row.platform.toLowerCase().includes(q) ||
                                 `day ${row.day}`.toLowerCase().includes(q) ||
                                 row.day.toString().includes(q);
                }

                return tabMatch && pillarMatch && searchMatch;
            });
        },

        generateCalendar() {
            const n = (this.niche || '').trim() || 'your product';
            
            // 30 distinct prompt templates maintaining exact ratio: 40% Educational (12), 30% Proof (9), 20% Story (6), 10% Offer (3)
            const templates = [
                { day: 1,  type: 'Educational', platform: 'LinkedIn',   format: 'Carousel / Slide Deck (5-7 Slides)', prompt: `3 costly mistakes people make in ${n} (and how to avoid them starting today)`, tip: 'Hook the audience on slide 1 with the pain point. Break down each mistake on slides 2-4 and provide the solution on slide 5.' },
                { day: 2,  type: 'Educational', platform: 'Twitter/X', format: 'Text Thread (4-6 Tweets)', prompt: `The step-by-step framework to simplify your ${n} workflow in 15 minutes a day`, tip: 'Use a bold hook tweet stating the outcome. List out actionable 1-2 sentence steps in bullet points for maximum retweets.' },
                { day: 3,  type: 'Proof',       platform: 'LinkedIn',   format: 'Text Post + Data Chart', prompt: `Case Study: How a real customer used structured ${n} strategies to double output`, tip: 'Include specific metric increases (e.g. +140% growth). Contrast the old struggling method with the new optimized framework.' },
                { day: 4,  type: 'Story',       platform: 'LinkedIn',   format: 'Personal Narrative Text Post', prompt: `The single hardest lesson I learned while building in the ${n} space`, tip: 'Start in media res (at the peak moment of struggle or tension). Share your vulnerability first before explaining the core realization.' },
                { day: 5,  type: 'Educational', platform: 'Twitter/X', format: 'Curated Resource List / Thread', prompt: `5 essential tools & resources every ${n} professional should bookmark in 2026`, tip: 'Tag or mention tool names clearly. Explain the exact single use-case for each tool so readers bookmark the post.' },
                { day: 6,  type: 'Offer',       platform: 'LinkedIn',   format: 'Direct Pitch + Screenshot Demo', prompt: `Why we built our custom ${n} solution and how you can try it risk-free today`, tip: 'Lead with the problem your tool solves, show 1 key screenshot, and end with a soft call-to-action asking readers to comment or link in bio.' },
                { day: 7,  type: 'Educational', platform: 'Facebook',  format: 'Longform Discussion Post', prompt: `The #1 myth about ${n} that is holding most people back from scaling`, tip: 'State the myth clearly in quotes. Provide 3 reasons why it fails and invite your audience to share their experience in comments.' },
                { day: 8,  type: 'Proof',       platform: 'LinkedIn',   format: 'Before vs After Comparison Graphic', prompt: `Before vs After: Key performance metrics achieved after optimizing ${n} processes`, tip: 'Use a 2-column image layout comparing baseline metrics vs current results. Keep caption focused on the pivotal process change.' },
                { day: 9,  type: 'Story',       platform: 'Twitter/X', format: 'Short Unfiltered Story Thread', prompt: `Behind the scenes: The unvarnished truth about starting our journey in ${n}`, tip: 'Focus on an authentic mistake or obstacle. Share real numbers or timeline milestones to build deep trust with followers.' },
                { day: 10, type: 'Proof',       platform: 'LinkedIn',   format: 'Teardown Analysis Post', prompt: `Teardown: 3 real-world examples of top-performing ${n} strategies in action`, tip: 'Deconstruct 3 industry leaders or campaigns. Highlight what made them work and how your audience can replicate the structure.' },
                { day: 11, type: 'Educational', platform: 'LinkedIn',   format: '5-Point Self-Audit Checklist', prompt: `How to audit your current ${n} strategy in 5 quick diagnostic steps`, tip: 'Format as a clear diagnostic checklist (e.g., [ ] Step 1). Ask readers to score themselves from 1 to 5 in comments.' },
                { day: 12, type: 'Educational', platform: 'Twitter/X', format: 'Bite-sized Insight Post', prompt: `The 80/20 rule applied to ${n}: Focus on these 2 key levers first`, tip: 'State the 20% input clearly. Emphasize why removing friction from these 2 levers yields 80% of total results.' },
                { day: 13, type: 'Proof',       platform: 'LinkedIn',   format: 'Client Case Study Spotlight', prompt: `Customer Spotlight: How an innovative brand achieved rapid growth in ${n}`, tip: 'Tag the customer or brand if possible. Highlight the exact timeframe (e.g. 60 days) it took to achieve the goal.' },
                { day: 14, type: 'Story',       platform: 'LinkedIn',   format: 'Reflective Founder Lesson', prompt: `A costly setback in ${n} that taught me more than any successful launch`, tip: 'Be brutally honest about what went wrong and how much money or time was lost. Share the exact rule created to prevent it.' },
                { day: 15, type: 'Educational', platform: 'Twitter/X', format: 'Actionable Hacks List', prompt: `7 non-obvious tactics to supercharge your ${n} outcomes this month`, tip: 'Focus on non-obvious tweaks that take under 5 minutes to implement. Use simple formatting with bullet points.' },
                { day: 16, type: 'Offer',       platform: 'LinkedIn',   format: 'Value-First Consultation Callout', prompt: `Ready to level up your ${n}? Here is how our team can help you get results fast`, tip: 'Offer a limited number of free audit sessions or teardowns. Frame the offer around instant value rather than a hard sale.' },
                { day: 17, type: 'Educational', platform: 'LinkedIn',   format: 'Standard Operating Procedure (SOP)', prompt: `The ultimate checklist for scaling your ${n} operations without quality drops`, tip: 'Write this as a plug-and-play template your audience can copy into Notion. Ask them to repost if they found it useful.' },
                { day: 18, type: 'Proof',       platform: 'LinkedIn',   format: 'Data-Driven Infographic / Text', prompt: `Data breakdown: The top metrics proving why dedicated ${n} strategy pays off`, tip: 'Highlight 1-2 statistical benchmarks. Use bold formatting for key metrics so skimmers immediately absorb the proof.' },
                { day: 19, type: 'Story',       platform: 'Twitter/X', format: 'Contrarian Industry Viewpoint', prompt: `What nobody tells you about building authority in the ${n} industry`, tip: 'Challenge popular advice with a counter-intuitive truth learned from experience. Ask followers if they agree or disagree.' },
                { day: 20, type: 'Proof',       platform: 'LinkedIn',   format: 'Multi-Testimonial Grid', prompt: `3 client testimonials showing what happens when you commit to ${n} consistency`, tip: 'Combine quotes from 3 different clients or users. Emphasize common themes like speed, relief, or revenue impact.' },
                { day: 21, type: 'Educational', platform: 'LinkedIn',   format: 'Critical Pitfall Warning', prompt: `Stop making this common oversight when executing your ${n} campaigns`, tip: 'Use a bold warning headline. Explain the hidden cost of the oversight and provide an immediate fix.' },
                { day: 22, type: 'Educational', platform: 'Twitter/X', format: 'Beginner Roadmap Thread', prompt: `The beginner's guide to mastering ${n} without feeling overwhelmed`, tip: 'Break down a complex topic into Phase 1, Phase 2, Phase 3. Keep vocabulary simple and accessible to newcomers.' },
                { day: 23, type: 'Proof',       platform: 'LinkedIn',   format: 'Milestone / Growth Update', prompt: `Milestone celebration: How disciplined ${n} execution brought us to where we are`, tip: 'Celebrate a key metric milestone (e.g. 10k users or 1M views). Express genuine gratitude and attribute success to customer feedback.' },
                { day: 24, type: 'Story',       platform: 'LinkedIn',   format: 'Brand Manifesto Post', prompt: `The core philosophy that drives everything we design and build in ${n}`, tip: 'State your top 3 non-negotiable principles. Explain why you refuse to cut corners in an industry filled with shortcuts.' },
                { day: 25, type: 'Educational', platform: 'Twitter/X', format: 'Quick Wins Checklist', prompt: `4 quick wins you can implement in ${n} before the end of this week`, tip: 'Focus on tasks that can be completed before Friday. Encourage followers to save or bookmark for their weekly review.' },
                { day: 26, type: 'Offer',       platform: 'LinkedIn',   format: 'Interactive Workflow Audit CTA', prompt: `Exclusive invitation: Get a personalized audit of your ${n} workflow today`, tip: 'Ask a diagnostic question (e.g. Struggling with X?). Invite interested readers to comment AUDIT to receive a custom teardown.' },
                { day: 27, type: 'Educational', platform: 'LinkedIn',   format: 'Future Industry Forecast', prompt: `Industry forecast: Where the ${n} space is heading over the next 12 months`, tip: 'Share 3 major trends expected over the next 12 months. Explain how smart teams can prepare today to stay ahead.' },
                { day: 28, type: 'Proof',       platform: 'Twitter/X', format: 'Micro-Case Study Post', prompt: `Quick win proof: Small adjustments in ${n} that yielded massive ROI`, tip: 'Share a tiny tweak that took 10 minutes but generated outsized engagement or conversions. Keep sentence structure punchy.' },
                { day: 29, type: 'Story',       platform: 'LinkedIn',   format: 'Evolution & Retrospective', prompt: `Looking back: How our perspective on ${n} has evolved over the years`, tip: 'Compare how you used to handle a problem 3 years ago vs how you handle it today. Highlight maturity and mindset shifts.' },
                { day: 30, type: 'Proof',       platform: 'LinkedIn',   format: 'Monthly Performance Recap', prompt: `Monthly recap: Full summary of results, wins, and key lessons in ${n}`, tip: 'Summarize top performing content, key lessons, and total reach achieved during the 30-day matrix. Invite questions.' }
            ];

            this.days = templates.map(t => ({
                day: t.day,
                pillar: t.type,
                prompt: t.prompt,
                platform: t.platform,
                format: t.format,
                tip: t.tip
            }));
        },

        copyPrompt(text, day) {
            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(text).then(() => {
                    this.copiedDay = day;
                    this.showToast(`Day ${day} prompt copied to clipboard!`);
                    setTimeout(() => { this.copiedDay = null; }, 2000);
                }).catch(() => {
                    this.fallbackCopy(text, day);
                });
            } else {
                this.fallbackCopy(text, day);
            }
        },

        fallbackCopy(text, day) {
            const textArea = document.createElement("textarea");
            textArea.value = text;
            textArea.style.position = "fixed";
            textArea.style.left = "-9999px";
            textArea.style.top = "-9999px";
            document.body.appendChild(textArea);
            textArea.focus();
            textArea.select();
            try {
                document.execCommand("copy");
                this.copiedDay = day;
                this.showToast(`Day ${day} prompt copied to clipboard!`);
                setTimeout(() => { this.copiedDay = null; }, 2000);
            } catch (err) {
                console.error("Fallback copy failed", err);
            }
            document.body.removeChild(textArea);
        },

        copyActiveWeekPrompts() {
            const list = this.filteredDays;
            if (!list || list.length === 0) return;

            const text = list.map(d => `Day ${d.day} [Pillar: ${d.pillar} | Platform: ${d.platform}]:\nPrompt: ${d.prompt}\nFormat: ${d.format}\nTip: ${d.tip}`).join('\n\n----------------------------------------\n\n');

            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(text).then(() => {
                    this.showToast(`Copied ${list.length} prompts to clipboard!`);
                });
            } else {
                const textArea = document.createElement("textarea");
                textArea.value = text;
                textArea.style.position = "fixed";
                textArea.style.left = "-9999px";
                textArea.style.top = "-9999px";
                document.body.appendChild(textArea);
                textArea.focus();
                textArea.select();
                try {
                    document.execCommand("copy");
                    this.showToast(`Copied ${list.length} prompts to clipboard!`);
                } catch (err) {
                    console.error("Copy active week failed", err);
                }
                document.body.removeChild(textArea);
            }
        },

        copyAllPrompts() {
            const text = this.days.map(d => `Day ${d.day} [Pillar: ${d.pillar} | Platform: ${d.platform}]:\nPrompt: ${d.prompt}\nFormat: ${d.format}\nTip: ${d.tip}`).join('\n\n----------------------------------------\n\n');

            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(text).then(() => {
                    this.showToast('Copied full 30-Day Content Calendar to clipboard!');
                });
            } else {
                const textArea = document.createElement("textarea");
                textArea.value = text;
                textArea.style.position = "fixed";
                textArea.style.left = "-9999px";
                textArea.style.top = "-9999px";
                document.body.appendChild(textArea);
                textArea.focus();
                textArea.select();
                try {
                    document.execCommand("copy");
                    this.showToast('Copied full 30-Day Content Calendar to clipboard!');
                } catch (err) {
                    console.error("Copy all failed", err);
                }
                document.body.removeChild(textArea);
            }
        },

        exportCsv() {
            const headers = ['Day', 'Pillar', 'Post Prompt', 'Target Platform', 'Recommended Format', 'Execution Tip'];

            const escapeCsv = (val) => {
                const str = String(val ?? '');
                return `"${str.replace(/"/g, '""')}"`;
            };

            const rows = this.days.map(row => [
                escapeCsv(`Day ${row.day}`),
                escapeCsv(row.pillar),
                escapeCsv(row.prompt),
                escapeCsv(row.platform),
                escapeCsv(row.format),
                escapeCsv(row.tip)
            ]);
            
            // UTF-8 BOM (\uFEFF) ensures Excel, Apple Numbers, and Google Sheets parse UTF-8 characters cleanly without garbled text
            const csvContent = '\uFEFF' + [headers.map(escapeCsv).join(','), ...rows.map(r => r.join(','))].join('\r\n');
            const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
            const url = URL.createObjectURL(blob);
            
            const link = document.createElement("a");
            const safeNiche = (this.niche || 'Niche').trim().replace(/[^a-zA-Z0-9]/g, '_') || 'Niche';
            link.setAttribute("href", url);
            link.setAttribute("download", `30_Day_Content_Calendar_${safeNiche}.csv`);
            
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            this.showToast(`Downloaded 30_Day_Content_Calendar_${safeNiche}.csv`);
        }
    }
}
</script>
@endsection
